### ISSUE TITLE
addressing how this app receives inputs

### ISSUE THREAD

**Issue by francopestilli** [brainlife/app-FSLTopupEddy#1]
hi @bacaron 

what happen in these lines if only one of the two input DWI has b0 volumes?
https://github.com/brainlife/app-FSLTopupEddy/blob/3c2182a4c2093373ef5e5a27333daa23c7fd03df/topup_eddy.sh#L62

**Comment by francopestilli** [comment]
hi @bacaron what happens if the input DWI has no diffusion-weighted directions, but instead it only contains B0 data? @svincibo

**Comment by bacaron** [comment]
@francopestilli I've never tested it, but those lines should just grab the b0s even if that's all there is.

I can test to confirm, but it should still work in theory. 

If the volume has no b0s, then it will most likely error out. Again, need to confirm that though.

**Comment by francopestilli** [comment]
thanks @bacaron
